name: Rust
on:
  push:
    branches:
      - master
  pull_request: null
env:
  CARGO_INCREMENTAL: 0
  CARGO_NET_RETRY: 10
  RUSTFLAGS: '-D warnings'
  RUSTUP_MAX_RETRIES: 10
  RUST_BACKTRACE: short
jobs:
  rust:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    runs-on: '${{ matrix.os }}'
    steps:
      - uses: actions/checkout@v3
      - uses: Swatinem/rust-cache@v2
      - name: Install Rust toolchain
        run: |
          rustup update --no-self-update nightly
          rustup component add rustfmt clippy
      - name: Build
        run: cargo build
      - name: Run tests
        run: cargo test
      - name: Run clippy
        run: cargo clippy
      - name: Run fmt
        run: cargo fmt --check
